[package]
name = "pnpid"
version = "0.1.0"
edition = "2021"

[build-dependencies]
csv = "1.3"
prettyplease = "0.2.25"
quote = "1.0.37"
serde = { version = "1.0.214", features = ["derive"] }
syn = { version = "2.0.87", default-features = false }
